### ISSUE TITLE
Line spacing within & between messages changed (CSS regression)

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/monorepo#577]
The line spacing within and between messages changed making messages less readable.  

Ideally it should be smaller within a message, and wider between messages (including between grouped messages).

If that's difficult, it should return to the previous spacing, which was fine. 

Also, did our CSS regression tests (chromatic?) catch this?

**Comment by siepra** [comment]
Our regression test caught it in fact, but still such tests requires our 'supervision' and we simply missed that because of other corresponding changes to the same components. I can't really tell what caused the change though. It happened during introducing images sending but our tests were down for some time so it's hard to point out the exact commit

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/monorepo/pull/579

**Comment by holmesworcester** [comment]
Will Chromatic tests block merging, until approved? Do they run fast enough for this to be practical? Let's make them block merging if they don't already and it's practical.

**Comment by siepra** [comment]
Every time base snapshots doesn't match current snapshot it requires someone's approval

**Comment by holmesworcester** [comment]
So merge will not be possible unless it is approved?

**Comment by kingalg** [comment]
Looks good and readable.
