### ISSUE TITLE
New messages indicator

### ISSUE THREAD

**Issue by siepra** [TryQuiet/monorepo#629]

**Comment by siepra** [comment]
Related issue https://github.com/TryQuiet/monorepo/issues/606

**Comment by EmiM** [comment]
Fix: https://github.com/TryQuiet/monorepo/pull/632

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/monorepo/pull/612

**Comment by kingalg** [comment]
v 0.8.3-alpha.0

Implemented on all systems.

@holmesworcester @siepra I wanted to check how this button is acting with different size of the window and I see that resizing the window is closing this button. As I don't have any description for this I wanted to make sure that this is planned and expected behaviour before I close this task.

<img width="331" alt="Screenshot 2022-06-22 at 12 05 16" src="https://user-images.githubusercontent.com/68909168/175002964-b9bbdfbe-5d5f-40da-ba8a-03201f0a0cbb.png">

**Comment by siepra** [comment]
Resizing the window should scroll channel view to the bottom, which means indicator disappears as well
